/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Trial.Store;

import javax.swing.JOptionPane;
import Main.MainActivity;
import java.awt.Font;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Savepoint;
import java.sql.Statement;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;

/**
 *
 * @author DELL
 */
public class AddProductActivity extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public AddProductActivity() {
        initComponents();
           UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
                "Arial", Font.BOLD, 18)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        productName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        productPrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        productSalePrice = new javax.swing.JTextField();
        addProduct = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("إضافة منتج ");
        setLocation(new java.awt.Point(100, 100));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setLayout(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 11, 106));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("إضافة منتج");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(520, 80, 200, 100);

        jPanel2.setBackground(new java.awt.Color(0, 11, 106));
        jPanel2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("محلات أبودان للأدوات الكهربائية");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(40, 20, 260, 29);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-conflict-48.png"))); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(120, 50, 50, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(-10, 0, 910, 130);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("الاسم :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(680, 240, 80, 29);

        productName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        productName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(productName);
        productName.setBounds(370, 230, 250, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("سعر الجملة :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(650, 320, 110, 29);

        productPrice.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        productPrice.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        productPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productPriceActionPerformed(evt);
            }
        });
        jPanel1.add(productPrice);
        productPrice.setBounds(470, 310, 150, 40);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("الكمية :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(680, 400, 80, 29);

        quantity.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        quantity.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(quantity);
        quantity.setBounds(470, 390, 150, 40);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("سعر البيع :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(330, 320, 110, 29);

        productSalePrice.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        productSalePrice.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        productSalePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productSalePriceActionPerformed(evt);
            }
        });
        jPanel1.add(productSalePrice);
        productSalePrice.setBounds(180, 310, 150, 40);

        addProduct.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        addProduct.setText("إضافة");
        addProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductActionPerformed(evt);
            }
        });
        jPanel1.add(addProduct);
        addProduct.setBounds(60, 500, 160, 37);

        jPanel4.setBackground(new java.awt.Color(0, 11, 106));

        back.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setText("رجوع");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(30, 140, 110, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productSalePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productSalePriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productSalePriceActionPerformed

    private void productPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productPriceActionPerformed

    private void addProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductActionPerformed

  if(productName.getText().isEmpty()){
           JOptionPane.showMessageDialog(this, "اسم المنتج مطلوب");
           return;
        }

          if(productPrice.getText().isEmpty()){
           JOptionPane.showMessageDialog(this, "سعر الجملة مطلوب");
           return;
        }

            if(productSalePrice.getText().isEmpty()){
           JOptionPane.showMessageDialog(this, "سعر البيع مطلوب");
           return;
        }

              if(quantity.getText().isEmpty()){
           JOptionPane.showMessageDialog(this, "الكمية مطلوبة");
           return;
        }


               try {
    Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            // set this to a MS Access DB you have on your machine

    File f = new File("AboDan shops.accdb");
    String path= f.getAbsolutePath();

          //  now we can get the connection from the DriverManager
          String database= "jdbc:ucanaccess://"+path;

  Connection con = DriverManager.getConnection( database ,"","");
 PreparedStatement ps = con.prepareStatement("insert into Products (PRODUCT_NAME,PRODUCT_PRICE,PRODAUCT_SALE_PRICE,QUANTITY) values(?,?,?,?)");


     ps.setString(1,productName.getText());
       ps.setDouble(2,Double.valueOf(productPrice.getText()));
         ps.setDouble(3,Double.valueOf(productSalePrice.getText()));
       ps.setInt(4,Integer.parseInt(quantity.getText()));

      ps.addBatch();
      ps.clearParameters();

    con.setAutoCommit(false);

 Savepoint   point1=con.setSavepoint() ;
    int [] updateCounts=  ps.executeBatch();

      Savepoint   point2=con.setSavepoint() ;
      Statement s1 = con.createStatement();
//      

// con.rollback(point2);

   con.commit();

                 JOptionPane.showMessageDialog(this, "تمت العملية بنجاح");
                 productSalePrice.setText("");
                 productName.setText("");
                 productPrice.setText("");
                 quantity.setText("");

        }

            catch (Exception e) {
            	e.printStackTrace();
           // System.out.println("Error: " + e);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_addProductActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked

            this.setVisible(false);
            new MainActivity ().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProduct;
    private javax.swing.JLabel back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField productName;
    private javax.swing.JTextField productPrice;
    private javax.swing.JTextField productSalePrice;
    private javax.swing.JTextField quantity;
    // End of variables declaration//GEN-END:variables
}
